// gen_assets.mjs — Pack all x16-hero graphics/level assets + music into one
// assets.blob placed at a fixed HDV block, and emit src/asset_table.h.
//
// The blob layout (each entry has a skip count for the CX16 2-byte load-address
// header present on most .BIN resources):
//   TILES, SPRITE0, SPRITE1, FONT, PAL, MAP0..MAP10, MUSIC
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(__dirname, "..")
const dataDir = "C:/dev/x16-hero"
const buildDir = path.join(projectRoot, "build")

const ASSETS = [
  { key: "TILES",  file: "TILES.BIN",  skip: 2 },
  { key: "SPRITE0", file: "SPRITE0.BIN", skip: 2 },
  { key: "SPRITE1", file: "SPRITE1.BIN", skip: 2 },
  { key: "FONT",   file: "FONT.BIN",   skip: 0 },
  { key: "PAL",    file: "PAL.BIN",    skip: 2 },
  // MAP0..MAP10 — level tilemaps.  Raw tilemap data (2 bytes/tile).
  // mapN.bin has a 2-byte load-address header (like TILES/PAL); skip it.
]
for (let i = 0; i <= 10; i++) {
  ASSETS.push({ key: `MAP${i}`, file: `map${i}.bin`, skip: 2 })
}
// MUSIC — the packed ZSM->PSG blob from gen_music.mjs (in build/).
ASSETS.push({ key: "MUSIC", file: path.join(buildDir, "music.blob"), skip: 0 })

if (!fs.existsSync(buildDir)) fs.mkdirSync(buildDir, { recursive: true })

const blob = []
const table = []
let offset = 0

for (const a of ASSETS) {
  const src = path.isAbsolute(a.file) ? a.file : path.join(dataDir, a.file)
  const raw = fs.readFileSync(src)
  const data = raw.subarray(a.skip)
  blob.push(data)
  table.push({ key: a.key, offset, length: data.length })
  console.log(`  ${a.key.padEnd(10)} ${String(data.length).padStart(6)}B  (offset ${offset})`)
  offset += data.length
}

fs.writeFileSync(path.join(buildDir, "assets.blob"), Buffer.concat(blob))
console.log(`  Total assets.blob: ${offset} bytes`)

let cCode = `// AUTO-GENERATED by tools/gen_assets.mjs — do not edit.
#pragma once
#include <stdint.h>

typedef struct {
    const char *key;
    uint32_t offset;
    uint32_t length;
} AssetEntry;

#define ASSET_COUNT ${table.length}
static const AssetEntry assetTable[ASSET_COUNT] = {
${table.map((t) => `    { "${t.key}", ${t.offset}, ${t.length} },`).join("\n")}
};
`
fs.writeFileSync(path.join(projectRoot, "src", "asset_table.h"), cCode)
console.log(`  Wrote src/asset_table.h`)
