// AUTO-GENERATED by tools/gen_assets.mjs — do not edit.
#pragma once
#include <stdint.h>

typedef struct {
    const char *key;
    uint32_t offset;
    uint32_t length;
} AssetEntry;

#define ASSET_COUNT 17
static const AssetEntry assetTable[ASSET_COUNT] = {
    { "TILES", 0, 11648 },
    { "SPRITE0", 11648, 3328 },
    { "SPRITE1", 14976, 8448 },
    { "FONT", 23424, 1760 },
    { "PAL", 25184, 512 },
    { "MAP0", 25696, 4096 },
    { "MAP1", 29792, 2048 },
    { "MAP2", 31840, 2048 },
    { "MAP3", 33888, 2048 },
    { "MAP4", 35936, 2048 },
    { "MAP5", 37984, 2048 },
    { "MAP6", 40032, 2048 },
    { "MAP7", 42080, 2048 },
    { "MAP8", 44128, 2048 },
    { "MAP9", 46176, 2048 },
    { "MAP10", 48224, 2048 },
    { "MUSIC", 50272, 39963 },
};
