// AUTO-GENERATED by tools/gen_music.mjs — do not edit.
#pragma once
#include <stdint.h>

typedef struct {
    const char *name;
    uint16_t offset;
    uint16_t length;
    uint16_t loop_offset;
} MusicTrack;

#define MUSIC_TRACK_COUNT 5
static const MusicTrack musicTracks[MUSIC_TRACK_COUNT] = {
    { "TITLE", 0, 22468, 479 },
    { "HIGHSCORE", 22468, 12330, 311 },
    { "GAMEOVER", 34798, 289, 0 },
    { "KILLED", 35087, 683, 0 },
    { "LEVELCOMPLETE", 35770, 973, 0 },
};
