// AUTO-GENERATED by tools/gen_music.mjs — do not edit.
#pragma once
#include <stdint.h>

typedef struct {
    const char *name;
    uint16_t offset;
    uint16_t length;
} MusicTrack;

#define MUSIC_TRACK_COUNT 5
static const MusicTrack musicTracks[MUSIC_TRACK_COUNT] = {
    { "TITLE", 0, 21649 },
    { "HIGHSCORE", 21649, 16188 },
    { "GAMEOVER", 37837, 289 },
    { "KILLED", 38126, 726 },
    { "LEVELCOMPLETE", 38852, 1111 },
};
